name: Compile LaTeX on PR

on: 
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./03_Final_report_and_presentation
    steps:
    - uses: actions/checkout@v2
    - name: Compile Interim Report
      uses: xu-cheng/latex-action@v2
      with:
        root_file: interim_report.tex
        working_directory: ./03_Final_report_and_presentation
    - name: Compile Final Report
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: ./03_Final_report_and_presentation

