name: Compile and Release LaTeX on Master

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./03_Final_report_and_presentation
    steps:
    - uses: actions/checkout@v2
    - name: Compile Interim Report
      uses: xu-cheng/latex-action@v2
      with:
        root_file: interim_report.tex
        working_directory: ./03_Final_report_and_presentation
    - name: Compile Final Report
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: ./03_Final_report_and_presentation
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-PDF
        path: ./03_Final_report_and_presentation/interim_report.pdf
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Generate Tag
      id: generate_tag
      run: echo "##[set-output name=tag;]release-$(date +'%Y%m%d%H%M%S')"
      shell: bash
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.generate_tag.outputs.tag }}
        release_name: Release ${{ steps.generate_tag.outputs.tag }}
        draft: false
        prerelease: false
        body: 'New release of Interim Report'
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./03_Final_report_and_presentation/interim_report.pdf
        asset_name: interim_report.pdf
        asset_content_type: application/pdf
